name: CD with Gradle

on:
  push:
    branches: [ "develop" ]


# 코드의 내용을 이 파일을 실행하여 action을 수행하는 주체(Github Actions에서 사용하는 VM)가 읽을 수 있도록 허용합니다.
permissions:
  contents: read

# 실제 실행될 내용들을 정의합니다.
jobs:
  build:
    runs-on: ubuntu-latest # ubuntu 최신 버전에서 script를 실행

    steps:
      # 지정한 저장소(현재 REPO)에서 코드를 워크플로우 환경으로 가져오도록 하는 github action
      - uses: actions/checkout@v3

      # open jdk 11 버전 환경을 세팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: "adopt"

      # 테스트서버의 application-secret.yml생성.
      - name: make application-secret.yml(DEVELOP)
        if: github.ref == 'refs/heads/develop'
        run: |
          # spring의 resources 경로로 이동
          cd ./src/main/resources

          # 해당 디렉토리에 application-secret.yml 파일이 이미 존재하는지 확인하고, 없으면 생성합니다.
          if [ ! -f application-secret.yml ]; then
          touch ./application-secret.yml
          fi

          # GitHub Actions에서 설정한 값을 base64 디코딩하여 application-secret.yml 파일에 쓰기
          echo "copy properties"
          echo "${{ secrets.APPLICATION_SECRET_YML }}" | base64 --decode > ./application-secret.yml
        shell: bash

      # 테스트서버의 application.yml생성
      - name: make application.yml(DEVELOP)
        if: github.ref == 'refs/heads/develop'
        run: |
          # spring의 resources 경로로 이동
          cd ./src/main/resources

          # 해당 디렉토리에 application.yml 파일이 이미 존재하는지 확인하고, 없으면 생성합니다.
          if [ ! -f application.yml ]; then
          touch ./application.yml
          fi

          # GitHub Actions에서 설정한 값을 base64 디코딩하여 application.yml 파일에 쓰기
          echo "copy properties"
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > ./application.yml
        shell: bash

      # Gradle을 사용하여 소스를 빌드
      - name: Build with Gradle (DEVELOP)
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # Docker Hub에 로그인
      - name: Login to Docker Hub (DEVELOP)
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지를 빌드
      - name: Build Docker (DEVELOP)
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/develop-image .

      # Docker 이미지를 Docker Hub에 푸시합니다
      - name: Push Docker (DEVELOP)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/develop-image:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 대상 IP를 설정
      - name: Set target IP (DEVELOP)
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.DEVELOP_EC2_IP }}/api/env")
          echo $STATUS
          if [ $STATUS = 200 ]; then
            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.DEVELOP_EC2_IP }}/api/env")
          else
            CURRENT_UPSTREAM=green
          fi
          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
          if [ $CURRENT_UPSTREAM = blue ]; then
            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
          elif [ $CURRENT_UPSTREAM = green ]; then
            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
          else
            echo "error"
            exit 1
          fi

      # Docker Compose를 사용하여 컨테이너를 배포
      - name: Docker compose (DEVELOP)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.DEVELOP_EC2_IP }}
          key: ${{ secrets.DEVELOP_EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/develop-image:latest
            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d

      # 배포된 서버 URL을 확인
      - name: Check deploy server URL (DEVELOP)
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.DEVELOP_EC2_IP }}:${{env.STOPPED_PORT}}/api/env
          max-attempts: 5
          retry-delay: 10s

      # Nginx의 upstream을 변경
      - name: Change nginx upstream (DEVELOP)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.DEVELOP_EC2_IP }}
          key: ${{ secrets.DEVELOP_EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker exec -i nginxDevelopServer bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload'

      # 현재 서버를 중지
      - name: Stop current server (DEVELOP)
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.DEVELOP_EC2_IP }}
          key: ${{ secrets.DEVELOP_EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo docker stop ${{env.CURRENT_UPSTREAM}}
            sudo docker rm ${{env.CURRENT_UPSTREAM}}